
# class orang :
#     def __init__(self, name, age):
#         self.name =name
#         self.age = age
#     def myfunc(self):
#         print("halo nama saya " + self.name)
# p1 = orang("joni", 21)

# p1= orang('jono ', 22)
# p1.myfunc()







# class orang1 :
#     def __init__(slf, name, age):
#         slf.name =name
#         slf.age = age
#     def myfunc(abc):
#         print("halo nama saya" + abc.name)


# p1= orang1('joni ', 22)
# p1.myfunc()
# p1.age =27  #menganti  properti
# del p1.age  #menghapus properti
# del p1      #menghapus objek




# class kucing:
#     warna = None
#     usia  = None

# kucing1=kucing()
# kucing1.warna="hitam"
# kucing1.usia ="3 bulan"

# kucing2=kucing()
# kucing2.warna="putih"
# kucing2.usia ="2 bulan"

# kucing3=kucing()
# kucing3.warna="oren"
# kucing3.usia ="3.5 bulan"

# print(kucing1.warna, kucing1.usia)
# print(kucing2.warna, kucing2.usia)
# print(kucing3.warna, kucing3.usia)



# class mhs:
#     nama = None
#     asal = None
#     def perkenalan (self):
#         print(f'perkenalkan nama saya {self.nama} dari {self.asal}')

# deni = mhs()
# deni.nama= "tono"
# deni.asal= "jateng"

# lendis = mhs()
# lendis.nama= "lendis febri"
# lendis.asal= "jabar"


# deni.perkenalan()
# lendis.perkenalan()



